// Generated by BUCKLESCRIPT VERSION 1.9.1, PLEASE EDIT WITH CARE
'use strict';

var Most  = require("most");
var Curry = require("bs-platform/lib/js/curry.js");

function unfold(f) {
  return (function (param) {
      return Most.unfold((function (x) {
                    var match = Curry._1(f, x);
                    if (match) {
                      var match$1 = match[0];
                      return {
                              value: match$1[0],
                              seed: match$1[1]
                            };
                    } else {
                      return {
                              done: /* true */1
                            };
                    }
                  }), param);
    });
}

function fromList(list) {
  return unfold((function (curList) {
                  if (curList) {
                    return /* Some */[/* tuple */[
                              curList[0],
                              curList[1]
                            ]];
                  } else {
                    return /* None */0;
                  }
                }))(list);
}

var Subject = /* module */[];

exports.unfold   = unfold;
exports.fromList = fromList;
exports.Subject  = Subject;
/* most Not a pure module */
