// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var Most = require("most");
var Curry = require("bs-platform/lib/js/curry.js");

function unfold(f) {
  return (function (param) {
      return Most.unfold((function (x) {
                    var match = Curry._1(f, x);
                    if (match !== undefined) {
                      var match$1 = match;
                      return {
                              value: match$1[0],
                              seed: match$1[1]
                            };
                    } else {
                      return {
                              done: true
                            };
                    }
                  }), param);
    });
}

function fromList(list) {
  return unfold((function (curList) {
                  if (curList) {
                    return /* tuple */[
                            curList[0],
                            curList[1]
                          ];
                  }
                  
                }))(list);
}

var Subject = /* module */[];

exports.unfold = unfold;
exports.fromList = fromList;
exports.Subject = Subject;
/* most Not a pure module */
